pruebas_ejemplo_homepage:
    path:     /hello/{name}
    defaults: { _controller: PruebasEjemploBundle:Default:index }

formulario:
  path:     /formulario
  defaults: { _controller: PruebasEjemploBundle:Default:formulario }

insertar:
  path:     /insertar/{title}/{description}/{content}
  defaults: { _controller: PruebasEjemploBundle:Default:insertar }
  
listar:
  path:     /listar
  defaults: { _controller: PruebasEjemploBundle:Default:listar }
  
actualizar:
  path:     /actualizar/{id}/{title}/{description}/{content}
  defaults: { _controller: PruebasEjemploBundle:Default:actualizar }
  
borrar:
  path:     /borrar/{id}
  defaults: { _controller: PruebasEjemploBundle:Default:borrar }
  
  