security:
    firewalls:
        identificarse:
          pattern: ^/*          
          anonymous: ~
          provider: users
          form_login:
            login_path: login
            check_path: /login_check
          logout:
            path: logout
            target: /

    providers:
        users:
            entity: { class: Web\BlogBundle\Entity\Users, property: email }
    
    access_control:
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/nuevo-post, roles: ROLE_USUARIO}
        - { path: ^/editar-post, roles: ROLE_USUARIO}
        - { path: ^/delete-post, roles: ROLE_USUARIO}
    
    encoders:
        Web\BlogBundle\Entity\Users: { algorithm: sha512, iterations: 10 }
         
            

    
    

    

    
       