Web\BlogBundle\Entity\Posts:
    type: entity
    table: posts
    indexes:
        fk_category_post:
            columns:
                - category_id
        fk_user_post:
            columns:
                - user_id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
        image:
            type: string
            nullable: true
            length: 255
            fixed: false
        content:
            type: string
            nullable: true
            length: 255
            fixed: false
        status:
            type: string
            nullable: true
            length: 50
            fixed: false
        date:
            type: date
            nullable: true
        time:
            type: time
            nullable: true
    manyToOne:
        category:
            targetEntity: Categories
            cascade: {  }
            mappedBy: null
            inversedBy: posts
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: posts
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        tagsPosts:
            targetEntity: TagsPosts
            mappedBy: post
            cascade: ["persist"]
    lifecycleCallbacks: {  }

