Web\BlogBundle\Entity\Tags:
    type: entity
    table: tags
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
