inicio:
    pattern:  /
    defaults: { _controller: WebBlogBundle:Posts:index, page:1 }

home:
    pattern:  /inicio/{page}
    defaults: { _controller: WebBlogBundle:Posts:index, page:1 }
    
registro:
    pattern:  /registro
    defaults: { _controller: WebBlogBundle:Default:index }

login:
  pattern: /login
  defaults: { _controller: WebBlogBundle:Default:login }

login_check:
   pattern: /login_check

logout:
  pattern: /logout

new_post:
  pattern: /nuevo-post
  defaults: { _controller: WebBlogBundle:Posts:new }
  
edit_post:
  pattern: /editar-post/{post}
  defaults: { _controller: WebBlogBundle:Posts:edit }
  
delete_post:
  pattern: /delete-post/{post}
  defaults: { _controller: WebBlogBundle:Posts:delete }
  